# Naive Bayes 실습

## 1. Gaussian Naive Bayes
- 데이터, 모듈 불러오기

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
import pandas as pd

In [3]:
iris = datasets.load_iris()
df_X = pd.DataFrame(iris.data)
df_Y = pd.DataFrame(iris.target)

In [4]:
df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [5]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

### model fit

In [8]:
gnb = GaussianNB()
fitted = gnb.fit(iris.data, iris.target) #(x,y)
y_pred = fitted.predict(iris.data)

In [10]:
fitted.predict_proba(iris.data)[[1,48,51,100]] #[0일 확률, 1일 확률, 2일 확률]

array([[1.00000000e+000, 1.51480769e-017, 2.34820051e-025],
       [1.00000000e+000, 2.63876217e-018, 2.79566024e-025],
       [7.27347795e-102, 9.45169639e-001, 5.48303606e-002],
       [3.23245181e-254, 6.35381031e-011, 1.00000000e+000]])

In [11]:
fitted.predict(iris.data)[[1,48,51,100]]

array([0, 0, 1, 2])

### confusion matrix 구하기

In [14]:
from sklearn.metrics import confusion_matrix

In [15]:
confusion_matrix(iris.target, y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

### Prior 설정하기

In [18]:
gnb2=GaussianNB(priors=[1/100,1/100, 98/100])
fitted2 = gnb2.fit(iris.data,iris.target)
y_pred2 = fitted2.predict(iris.data) #predict(x)
confusion_matrix(iris.target,y_pred2) 

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]])

In [20]:
gnb2=GaussianNB(priors=[1/100,98/100,1/100])
fitted2 = gnb2.fit(iris.data,iris.target)
y_pred2 = fitted2.predict(iris.data) #predict(x)
confusion_matrix(iris.target,y_pred2) 

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]])

## 2. Multinomial naive bayes
- 모듈 불러오기 및 데이터 생성

In [21]:
from sklearn.naive_bayes import MultinomialNB

In [23]:
import numpy as np
X = np.random.randint(5,size=(6,100))
y = np.array([1,2,3,4,5,6])

In [24]:
X

array([[2, 2, 2, 1, 4, 3, 4, 3, 0, 0, 0, 4, 1, 0, 1, 2, 2, 3, 2, 4, 2, 1,
        2, 4, 4, 1, 2, 2, 0, 3, 1, 2, 0, 4, 4, 1, 4, 3, 3, 1, 2, 3, 1, 0,
        2, 3, 3, 3, 2, 3, 4, 1, 1, 0, 2, 0, 2, 3, 3, 4, 2, 0, 1, 2, 4, 2,
        0, 1, 3, 2, 2, 1, 1, 4, 4, 1, 2, 3, 3, 4, 2, 2, 3, 0, 2, 0, 2, 3,
        1, 0, 4, 4, 0, 0, 4, 3, 2, 4, 4, 1],
       [1, 2, 4, 1, 0, 2, 0, 2, 1, 1, 4, 1, 4, 2, 4, 1, 3, 3, 4, 4, 2, 4,
        2, 0, 4, 2, 2, 4, 1, 3, 1, 3, 2, 1, 3, 2, 1, 4, 2, 3, 3, 2, 1, 2,
        1, 0, 3, 1, 1, 0, 3, 1, 3, 1, 0, 2, 1, 1, 1, 3, 4, 0, 3, 1, 0, 3,
        2, 2, 1, 4, 1, 2, 3, 1, 0, 2, 0, 2, 4, 2, 1, 2, 1, 0, 3, 2, 1, 1,
        1, 0, 1, 2, 2, 3, 3, 4, 4, 2, 3, 1],
       [4, 3, 0, 0, 4, 0, 3, 3, 1, 1, 0, 2, 2, 2, 4, 3, 4, 3, 1, 3, 3, 3,
        4, 0, 2, 4, 1, 2, 3, 2, 2, 3, 3, 3, 1, 0, 3, 3, 0, 2, 1, 1, 0, 3,
        4, 4, 3, 1, 0, 2, 2, 2, 1, 2, 2, 0, 1, 4, 3, 2, 3, 4, 2, 0, 4, 1,
        3, 3, 3, 0, 0, 0, 0, 2, 2, 1, 4, 3, 4, 1, 2, 1, 4, 3, 3, 3, 4, 1,
        4, 0, 4, 0, 4,

In [25]:
y

array([1, 2, 3, 4, 5, 6])

## Multinomial Naive Bayes 모델 생성

In [26]:
clf = MultinomialNB()
clf.fit(X,y)

MultinomialNB()

In [28]:
print(clf.predict(X[2:3]))

[3]


In [29]:
clf.predict_proba(X[2:3])

array([[2.37535991e-31, 5.35239170e-35, 1.00000000e+00, 3.84202423e-32,
        3.60000000e-32, 6.44967398e-40]])

## prior 변경하기

In [34]:
clf2 = MultinomialNB(class_prior = [0.1,0.5,0.1,0.1,0.1,0.1])
clf2.fit(X,y)

MultinomialNB(class_prior=[0.1, 0.5, 0.1, 0.1, 0.1, 0.1])

In [35]:
clf2.predict_proba(X[2:3])

array([[2.37535991e-31, 2.67619585e-34, 1.00000000e+00, 3.84202423e-32,
        3.60000000e-32, 6.44967398e-40]])